#!/bin/bash
echo "Terima Kasih Kerana Sudah Berlangganan Dengan Nobita95"
echo "===============================================";
echo " ";
if [ -e "/root/log-ban.txt" ]; then
echo "User yang diban oleh user-ban adalah";
echo "Waktu - Username - Jumlah Multilogin"
echo "-------------------------------------";
cat /root/log-ban.txt
else
echo " Tidak ada user yang melakukan pelanggaran"
echo " Atau"
echo " Script user-ban belum dijalankan"
fi
echo " ";
echo "===============================================";
echo "Terima Kasih Kerana Sudah Berlangganan Dengan Nobita95";
