#!/bin/bash

#!/bin/bash
# User Status
cd
wget http://autoscriptnobita.tk/MASTER7752/user-list
mv ./user-list /usr/local/bin/user-list
chmod +x /usr/local/bin/user-list

# instal Buat Akun SSH/OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/buatakun
mv ./buatakun /usr/bin/buatakun
chmod +x /usr/bin/buatakun

# instal Generate Akun SSH/OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/generate
mv ./generate /usr/bin/generate
chmod +x /usr/bin/generate

# instal Generate Akun Trial
cd
wget http://autoscriptnobita.tk/configdual7m/trial
mv ./trial /usr/bin/trial
chmod +x /usr/bin/trial

# instal  Ganti Password Akun SSH/VPN
cd
wget http://autoscriptnobita.tk/configdual7m/userpass
mv ./userpass /usr/bin/userpass
chmod +x /usr/bin/userpass

# instal Generate Akun SSH/OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/userrenew
mv ./userrenew /usr/bin/userrenew
chmod +x /usr/bin/userrenew

# instal Hapus Akun SSH/OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/userdelete
mv ./userdelete /usr/bin/userdelete
chmod +x /usr/bin/userdelete

# instal Cek Login Dropbear & OpenSSH
cd
wget http://autoscriptnobita.tk/configdual7m/userlogin
mv ./userlogin /usr/bin/userlogin
chmod +x /usr/bin/userlogin

# instal Cek Login Dropbear, OpenSSH & OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/userlogin
mv ./userlogin /usr/bin/userlogin
chmod +x /usr/bin/userlogin

# instal Auto Limit Multi Login
cd
wget http://autoscriptnobita.tk/configdual7m/autolimit
mv ./autolimit /usr/bin/autolimit
chmod +x /usr/bin/autolimit

# instal Auto Limit Script Multi Login
cd
wget http://autoscriptnobita.tk/configdual7m/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal Melihat detail user SSH & OpenVPN 
cd
wget http://autoscriptnobita.tk/configdual7m/userdetail
mv ./userdetail /usr/bin/userdetail
chmod +x /usr/bin/userdetail

# instal Delete Akun Expire
cd
wget http://autoscriptnobita.tk/configdual7m/deleteuserexpire
mv ./deleteuserexpire /usr/bin/deleteuserexpire
chmod +x /usr/bin/deleteuserexpire

# instal  Kill Multi Login
cd
wget http://autoscriptnobita.tk/configdual7m/autokilluser
mv ./autokilluser /usr/bin/autokilluser
chmod +x /usr/bin/autokilluser

# instal Auto Banned Akun
cd
wget http://autoscriptnobita.tk/configdual7m/userban
mv ./userban /usr/bin/userban
chmod +x /usr/bin/userban

# instal Unbanned Akun
cd
wget http://autoscriptnobita.tk/configdual7m/userunban
mv ./userunban /usr/bin/userunban
chmod +x /usr/bin/userunban

# instal Mengunci Akun SSH & OpenVPN
cd
wget http://autoscriptnobita.tk/configdual7m/userlock
mv ./userlock /usr/bin/userlock
chmod +x /usr/bin/userlock

# instal Membuka user SSH & OpenVPN yang terkunci
cd
wget http://autoscriptnobita.tk/configdual7m/userunlock
mv ./userunlock /usr/bin/userunlock
chmod +x /usr/bin/userunlock

# instal Melihat daftar user yang terkick oleh perintah user-limit
cd
wget http://autoscriptnobita.tk/configdual7m/loglimit
mv ./loglimit /usr/bin/loglimit
chmod +x /usr/bin/loglimit

# instal Melihat daftar user yang terbanned oleh perintah user-ban
cd
wget http://autoscriptnobita.tk/configdual7m/logban
mv ./logban /usr/bin/logban
chmod +x /usr/bin/logban

# instal Buat Akun PPTP VPN
cd
wget http://autoscriptnobita.tk/configdual7m/useraddpptp
mv ./useraddpptp /usr/bin/useraddpptp
chmod +x /usr/bin/useraddpptp

# instal Hapus Akun PPTP VPN
cd
wget http://autoscriptnobita.tk/configdual7m/userdeletepptp
mv ./userdeletepptp /usr/bin/userdeletepptp
chmod +x /usr/bin/userdeletepptp

# instal Lihat Detail Akun PPTP VPN
cd
wget http://autoscriptnobita.tk/configdual7m/detailpptp
mv ./detailpptp /usr/bin/detailpptp
chmod +x /usr/bin/detailpptp

# instal Cek login PPTP VPN
cd
wget http://autoscriptnobita.tk/configdual7m/userloginpptp
mv ./userloginpptp /usr/bin/userloginpptp
chmod +x /usr/bin/userloginpptp

# instal Lihat Daftar User PPTP VPN
cd
wget http://autoscriptnobita.tk/configdual7malluserpptp
mv ./alluserpptp /usr/bin/alluserpptp
chmod +x /usr/bin/alluserpptp

# instal Set Auto Reboot
cd
wget http://autoscriptnobita.tk/configdual7mautoreboot
mv ./autoreboot /usr/bin/autoreboot
chmod +x /usr/bin/autoreboot

# Install SPEED tES
apt-get install python
wget http://autoscriptnobita.tk/configdual7m/speedtest.py
chmod +x speedtest.py

# instal autolimitscript
cd
wget http://autoscriptnobita.tk/configdual7m/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal userdelete
cd
wget http://autoscriptnobita.tk/configdual7m/userdelete
mv ./userdelete /usr/bin/userdelete
chmod +x /usr/bin/userdelete

# Install Menu
cd
wget http://autoscriptnobita.tk/MASTER7752/menu
mv ./menu /usr/local/bin/menu
chmod +x /usr/local/bin/menu

#!/bin/bash


cd

sed -i '$ i\screen -AmdS limit /root/limit.sh' /etc/rc.local

sed -i '$ i\screen -AmdS ban /root/ban.sh' /etc/rc.local

sed -i '$ i\screen -AmdS limit /root/limit.sh' /etc/rc.d/rc.local

sed -i '$ i\screen -AmdS ban /root/ban.sh' /etc/rc.d/rc.local

echo "0 0 * * * root /usr/local/bin/user-expire" > /etc/cron.d/user-expire

echo "0 0 * * * root /usr/local/bin/user-expire-pptp" > /etc/cron.d/user-expire-pptp


cat > /root/ban.sh <<END3

#!/bin/bash

#/usr/local/bin/user-ban

END3


cat > /root/limit.sh <<END3

#!/bin/bash

#/usr/local/bin/user-limit

END3

rm -f /root/iplist.txt

rm -f /root/update

rm -f /root/debian7latest.sh

rm -f /root/debian7latest.sh.x

rm -f /root/ddos-deflate-master.zip

rm -f /root/.bash_history && history -c
