#!/bin/bash
read -p "Masukkan Username yang ingin anda hapus: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
userdel -f $username
clear
  echo "Terima Kasih Kerana Sudah Berlangganan Dengan Nobita95"
  echo " "
  echo "-----------------------------------------------"
  echo -e "Username ${blue}$username${NC} Sudah berhasil di ${red}HAPUS${NC}."
  echo -e "Akses Login untuk username ${blue}$username${NC} sudah dihapus"
  echo "-----------------------------------------------"
else
echo "Username tidak ditemukan di server anda"
    exit 1
fi